Nama                 : Hafidz Abdillah Masruri<br>
Batch   : HCK-18<br>
Dataset : [Dataset](https://archive.ics.uci.edu/dataset/222/bank+marketing)<br>
Notebook ini bertujuan untuk memubat model Classification untuk memprediksi nasabah yang gagal membayar bulan depan<br>
Deployment : [URL Deploy](https://huggingface.co/spaces/hfdzam/Prediction_M2)

=====================================================================================<br>

# 10. Model Inference

## 10.1 Import Library

In [1]:
#import libraries
import pandas as pd
import numpy as np
# from sklearn.preprocessing import MinMaxScaler
import pickle

Import Library

## 10.2 Load Model

In [2]:
with open('pipeline_model.pkl', 'rb') as file_1:
    best_estimatorrf = pickle.load(file_1)

Load model

## 11.3 Buat data dummy

In [3]:
df = pd.read_csv('bank.csv', delimiter=';')
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,4521.0,41.170095,10.576211,19.0,33.0,39.0,49.0,87.0
balance,4521.0,1422.657819,3009.638142,-3313.0,69.0,444.0,1480.0,71188.0
day,4521.0,15.915284,8.247667,1.0,9.0,16.0,21.0,31.0
duration,4521.0,263.961292,259.856633,4.0,104.0,185.0,329.0,3025.0
campaign,4521.0,2.793630,3.109807,1.0,1.0,2.0,3.0,50.0
pdays,4521.0,39.766645,100.121124,-1.0,-1.0,-1.0,-1.0,871.0
previous,4521.0,0.542579,1.693562,0.0,0.0,0.0,0.0,25.0

Memanggil describe untuk melihat min max kolom

In [4]:
#dummy
np.random.seed(5)

age = np.random.uniform(19,87,5)
balance = np.random.uniform(-3313,71188,5)
day = np.random.uniform(1,31,5)
duration = np.random.uniform(4,3025,5)
campaign = np.random.uniform(1,50,5)
pdays = np.random.uniform(-1,871,5)
previous = np.random.uniform(0,25,5)

job = np.random.choice(df.job.unique(),5)
marital = np.random.choice(df.marital.unique(),5)
education = np.random.choice(df.education.unique(),5)
default = np.random.choice(df.default.unique(),5)
housing = np.random.choice(df.housing.unique(),5)
loan = np.random.choice(df.loan.unique(),5)
contact = np.random.choice(df.contact.unique(),5)
month = np.random.choice(df.month.unique(),5)
poutcome = np.random.choice(df.poutcome.unique(),5)

Membuat dummy

In [5]:
datainf = {
    'age': age,
    'balance': balance,
    'day': day,
    'duration': duration,
    'campaign': campaign,
    # 'pdays': pd.Series(pdays).astype('Int64'),  # Convert to integer, handling -1 as NA
    'pdays': pdays,  # Convert to integer, handling -1 as NA
    'previous': previous,
    'job' : job,
    'marital': marital,
    'education': education,
    'default': default,
    'housing': housing,
    'loan': loan,
    'contact': contact,
    'month': month,
    'poutcome': poutcome
}

Membuat dummy pada variabel datainf

In [6]:
datainf = pd.DataFrame(datainf)
datainf

,age,balance,day,duration,campaign,pdays,previous,job,marital,education,default,housing,loan,contact,month,poutcome
0,34.095536,42262.529530,3.422238,832.015202,30.396531,124.711270,0.607664,unknown,divorced,unknown,yes,yes,yes,cellular,apr,success
1,78.209797,53747.901216,23.153209,1255.403993,14.025137,143.414415,5.113889,unknown,single,primary,yes,no,no,cellular,oct,unknown
2,33.056903,35309.658515,14.239277,898.457477,14.949608,839.547421,17.496090,blue-collar,single,tertiary,no,yes,yes,cellular,jul,unknown
3,81.465542,18798.934168,5.749296,1903.568273,13.425822,836.317696,19.487865,services,single,tertiary,yes,yes,no,unknown,jul,unknown
4,52.211961,10672.419256,27.398111,1755.690025,17.050633,163.297580,0.573327,admin.,single,tertiary,no,no,yes,telephone,jan,other

datainf menjadi dataframe

In [7]:
best_estimatorrf

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipe_num',
                                                  Pipeline(steps=[('minmaxscaler',
                                                                   MinMaxScaler())]),
                                                  ['duration', 'pdays',
                                                   'previous']),
                                                 ('pipe_cat',
                                                  Pipeline(steps=[('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['job', 'marital', 'housing',
                                                   'loan', 'contact', 'month',
                                                   'poutcome'])])),
                ('randomforestclassifier',
                 RandomForestClassifier(class_weight='balanced', max_depth=1000,
                                        min_samples_leaf=4,
                                        min_samples_split=10,
                                        random_state=42))])

In [8]:
inf_pred = best_estimatorrf.predict(datainf)
datainf['y'] = inf_pred
datainf

,age,balance,day,duration,campaign,pdays,previous,job,marital,education,default,housing,loan,contact,month,poutcome,y
0,34.095536,42262.529530,3.422238,832.015202,30.396531,124.711270,0.607664,unknown,divorced,unknown,yes,yes,yes,cellular,apr,success,1
1,78.209797,53747.901216,23.153209,1255.403993,14.025137,143.414415,5.113889,unknown,single,primary,yes,no,no,cellular,oct,unknown,1
2,33.056903,35309.658515,14.239277,898.457477,14.949608,839.547421,17.496090,blue-collar,single,tertiary,no,yes,yes,cellular,jul,unknown,1
3,81.465542,18798.934168,5.749296,1903.568273,13.425822,836.317696,19.487865,services,single,tertiary,yes,yes,no,unknown,jul,unknown,1
4,52.211961,10672.419256,27.398111,1755.690025,17.050633,163.297580,0.573327,admin.,single,tertiary,no,no,yes,telephone,jan,other,0

Prediksi dengan 5 data dummy mendapatkan nilai 4 diprediksi yes dan 1 No